version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      # La URL de la base de datos debe configurarse en Coolify
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge 