version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crm_inmuebles?schema=public
    depends_on:
      - db
    restart: always
    networks:
      - crm-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm_inmuebles
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local 